---

# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html

AWSTemplateFormatVersion: 2010-09-09

Mappings:

  RegionConfig:
    ap-southeast-2:
      JumpBoxAmi: ami-0692dea0a2f8a1b35  # Amazon Linux 2 5.10

Parameters:

  NamePrefix:
    Description: A prefix or namespace that can be used for some resources created or accessed by this template.
    Type: String

Resources:

  JumpBoxLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${NamePrefix}-jump-box-launch-template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvdf
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: 20
              VolumeType: gp2
        IamInstanceProfile:
          Name: !Ref JumpBoxInstanceProfile
        ImageId: !FindInMap [RegionConfig, !Ref AWS::Region, JumpBoxAmi]
        InstanceType: t3.micro
        SecurityGroupIds:
          - !Ref JumpBoxSecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${NamePrefix}-jump-box
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub ${NamePrefix}-jump-box
        UserData:
          Fn::Base64: >
            #!/bin/bash
            set -x
            yum update --assume-yes
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: !Sub ${NamePrefix}-jump-box

  JumpBoxInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref JumpBoxRole

  JumpBoxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore

  JumpBoxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${NamePrefix}-jump-box-security-group
      GroupDescription: Jump box security group
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0  # Outbound to anywhere.
      VpcId:
        Fn::ImportValue: !Sub ${NamePrefix}-vpc-id
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-jump-box-security-group

  JumpBoxAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${NamePrefix}-jump-box-auto-scaling-group
      DesiredCapacity: 1
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref JumpBoxLaunchTemplate
        Version: !GetAtt JumpBoxLaunchTemplate.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      VPCZoneIdentifier:
        - !Select [0, !Split [",", Fn::ImportValue: !Sub "${NamePrefix}-private-subnet-list"]]
        - !Select [1, !Split [",", Fn::ImportValue: !Sub "${NamePrefix}-private-subnet-list"]]
        - !Select [2, !Split [",", Fn::ImportValue: !Sub "${NamePrefix}-private-subnet-list"]]
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: !Sub ${NamePrefix}-jump-box
