---

AWSTemplateFormatVersion: 2010-09-09

Mappings:

  test:
    ap-southeast-2:
      AZ1: ap-southeast-2a
      AZ2: ap-southeast-2b
      AZ3: ap-southeast-2c
      JumpBoxAmi: ami-0692dea0a2f8a1b35  # Amazon Linux 2 5.10
      JumpBoxInstanceType: t3.micro
      JumpBoxAsgDesiredCapacity: 1
      JumpBoxAsgMaximumSize: 1
      JumpBoxAsgMinimumSize: 1
      JumpBoxVolumeSize: 20
      JumpBoxVolumeType: gp2

Parameters:

  Environment:
    Type: String
    Default: test

  NamePrefix:
    Description: A prefix or namespace that can be used for some resources created or accessed by this template.
    Type: String

Resources:

  JumpBoxLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${NamePrefix}-JumpBoxLaunchTemplate
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvdf
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: !FindInMap [!Ref Environment, !Ref AWS::Region, "JumpBoxVolumeSize"]
              VolumeType: !FindInMap [!Ref Environment, !Ref AWS::Region, "JumpBoxVolumeType"]
        IamInstanceProfile:
          Name: !Ref JumpBoxInstanceProfile
        ImageId: !FindInMap [!Ref Environment, !Ref AWS::Region, "JumpBoxAmi"]
        InstanceType: !FindInMap [!Ref Environment, !Ref AWS::Region, "JumpBoxInstanceType"]
        SecurityGroupIds:
          - !Ref JumpBoxSecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: JumpBox
              - Key: NamePrefix
                Value: !Ref NamePrefix
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: JumpBox
              - Key: NamePrefix
                Value: !Ref NamePrefix
        UserData:
          Fn::Base64: >
            #!/bin/bash -x
            yum update -y
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: JumpBox
            - Key: NamePrefix
              Value: !Ref NamePrefix

  JumpBoxInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref JumpBoxRole

  JumpBoxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-JumpBox
        - Key: NamePrefix
          Value: !Ref NamePrefix

  JumpBoxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${NamePrefix}-JumpBoxSecurityGroup
      GroupDescription: JumpBox Security Group
      SecurityGroupEgress: []
      SecurityGroupIngress: []
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-JumpBoxSG
        - Key: NamePrefix
          Value: !Ref NamePrefix
      VpcId:
        Fn::ImportValue: !Sub ${NamePrefix}-vpc-id

  JumpBoxAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${NamePrefix}-JumpBoxAutoScalingGroup
      AvailabilityZones:
        - Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "AZ1" ]
        - Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "AZ2" ]
        - Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "AZ3" ]
      DesiredCapacity:
        Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "JumpBoxAsgDesiredCapacity" ]
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref JumpBoxLaunchTemplate
        Version: !GetAtt JumpBoxLaunchTemplate.LatestVersionNumber
      MaxSize:
        Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "JumpBoxAsgMaximumSize" ]
      MinSize:
        Fn::FindInMap: [ Ref: Environment, Ref: AWS::Region, "JumpBoxAsgMinimumSize" ]
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: JumpBox
        - Key: NamePrefix
          PropagateAtLaunch: true
          Value: !Ref NamePrefix
      VPCZoneIdentifier:
        - Fn::Select:
          - 0
          - !Split
            - ','
            - Fn::ImportValue: !Sub ${NamePrefix}-private-subnet-list
        - Fn::Select:
          - 1
          - !Split
            - ','
            - Fn::ImportValue: !Sub ${NamePrefix}-private-subnet-list
        - Fn::Select:
          - 2
          - !Split
            - ','
            - Fn::ImportValue: !Sub ${NamePrefix}-private-subnet-list
