---

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions

Parameters:

  NamePrefix:
    Description: A prefix or namespace that can be used for some resources created or accessed by this template.
    Type: String

  DbAdminUser:
    Description: Name of the DB admin user.
    Type: String
    Default: admin

  DbProxyUser:
    Description: Name of the DB proxy user.
    Type: String
    Default: proxy

Resources:

  ###################
  # Security Groups #
  ###################

  RDSAuroraDbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow TCP to Aurora RDS 3306
      GroupName: !Sub ${NamePrefix}-RDSAuroraTcpMySQLPrivateRestricted
      VpcId:
        Fn::ImportValue: !Sub ${NamePrefix}-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp:
            Fn::ImportValue: !Sub ${NamePrefix}-restricted-subnet-cidr
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp:
            Fn::ImportValue: !Sub ${NamePrefix}-private-subnet-cidr
      SecurityGroupEgress: []
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-DbSG

  ###################
  # DB Subnet Group #
  ###################

  RDSAuroraServerlessV2DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${NamePrefix} Aurora Serverless v2 DB Subnet Group
      DBSubnetGroupName: !Sub ${NamePrefix}-db-aurora-serverless-v2-subnet-group
      SubnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub ${NamePrefix}-restricted-subnet-list

  ##########
  # DB CMK #
  ##########

  DBCMK:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub CMK for ${NamePrefix} database
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: "root"
        Statement:
          - Sid: "Delegate to IAM"
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  DBCMKAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${NamePrefix}-db-cmk
      TargetKeyId: !Ref DBCMK

  ############
  # DB Creds #
  ############

  # @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html

  # Admin
  DBAdminCredentials:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Admin credentials for the ${NamePrefix} database.
      GenerateSecretString:
        SecretStringTemplate: !Sub '{ "username": "${DbAdminUser}" }'
        ExcludePunctuation: true
        ExcludeCharacters: '''"@/\'
        GenerateStringKey: "password"
        PasswordLength: 30
      Name: !Sub ${NamePrefix}/rds/${DbAdminUser}

  DBAdminCredentialsAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBAdminCredentials
      TargetId: !Ref RdsAuroraServerlessV2Cluster
      TargetType: AWS::RDS::DBCluster

  # RDS Proxy
  DBApiCredentials:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub RDS Proxy credentials for the ${NamePrefix} database.
      GenerateSecretString:
        SecretStringTemplate: !Sub '{ "username": "${DbProxyUser}" }'
        ExcludePunctuation: true
        ExcludeCharacters: '''"@/\'
        GenerateStringKey: "password"
        PasswordLength: 30
      Name: !Sub ${NamePrefix}/rds/${DbProxyUser}

  DBApiCredentialsAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBApiCredentials
      TargetId: !Ref RdsAuroraServerlessV2Cluster
      TargetType: AWS::RDS::DBCluster

  ###################
  # DB Param Groups #
  ###################

  RdsAuroraServerlessV2ClusterPG:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub Cluster Parameter Group for ${NamePrefix} DB
      Family: aurora-mysql8.0
      Parameters:
        time_zone: UTC

  RdsAuroraServerlessV2ClusterInstancePG:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub Instance Parameter Group for ${NamePrefix} DB
      Family: aurora-mysql8.0
      Parameters:
        explicit_defaults_for_timestamp: 1

  ############################
  # DB v2 Serverless Cluster #
  ############################

  # @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html

  RdsAuroraServerlessV2Cluster:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: 35
      DBClusterIdentifier: !Sub ${NamePrefix}-aurora-mysql-serverless-v2
      DBSubnetGroupName: !Ref RDSAuroraServerlessV2DBSubnetGroup
      DBClusterParameterGroupName: !Ref RdsAuroraServerlessV2ClusterPG
      VpcSecurityGroupIds:
        - !Ref RDSAuroraDbSecurityGroup
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.02.0
      EnableIAMDatabaseAuthentication: true
      EnableCloudwatchLogsExports:
        - audit
        - general
        - error
        - slowquery
      StorageEncrypted: true
      KmsKeyId: !GetAtt DBCMK.Arn
      MasterUsername: !Sub "{{resolve:secretsmanager:${DBAdminCredentials}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBAdminCredentials}:SecretString:password}}"
      ServerlessV2ScalingConfiguration:
        MinCapacity: 2
        MaxCapacity: 5
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-mysql-serverless-v2-db

  # @see https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html

  RdsAuroraServerlessV2DbInstance1:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.02.0
      DBClusterIdentifier: !Ref RdsAuroraServerlessV2Cluster
      DBInstanceClass: db.serverless
      CACertificateIdentifier: rds-ca-2019
      DBSubnetGroupName: !Ref RDSAuroraServerlessV2DBSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-mysql-serverless-v2-db-instance

Outputs:

  AuroraName:
    Description: Aurora Name
    Export:
      Name: !Sub ${NamePrefix}-aurora-cluster-name
    Value: !Ref RdsAuroraServerlessV2Cluster

  RdsAuroraServerlessV2ClusterName:
    Description: Aurora Name
    Export:
      Name: !Sub ${NamePrefix}-aurora-serverlessv2-cluster-name
    Value: !Ref RdsAuroraServerlessV2Cluster

  DBApiCredentials:
    Description: DB Api Creds ARN
    Export:
      Name: !Sub ${NamePrefix}-db-api-creds-arn
    Value: !Ref DBApiCredentials
